# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDm8WcmJL4jZhOa83AXgxeWY5ECaHOub
"""
!pip install pytelegrambotapi

import telebot
from telebot import types
from datetime import datetime
import matplotlib.pyplot as plt

MY_TOKEN = "8590324035:AAEIFPKl9zXyXfoch3zGNIG3yT8bvwB_4-0"

bot = telebot.TeleBot(MY_TOKEN)

user_expenses = {}
user_savings = {}

CATEGORIES = {
    "еда": "Food",
    "food": "Food",
    "кофе": "Food",
    "coffee": "Food",
    "restaurant": "Food",
    "кафе": "Food",
    "transport": "Transport",
    "транспорт": "Transport",
    "taxi": "Transport",
    "такси": "Transport",
    "bus": "Transport",
    "автобус": "Transport",
    "metro": "Transport",
    "entertainment": "Entertainment",
    "развлечения": "Entertainment",
    "movie": "Entertainment",
    "кино": "Entertainment",
    "games": "Entertainment",
    "sport": "Sport",
    "спорт": "Sport",
    "gym": "Sport",
    "fitness": "Sport",
    "education": "Education",
    "учеба": "Education",
    "books": "Education",
    "course": "Education",
    "clothes": "Clothes",
    "одежда": "Clothes",
    "shoes": "Clothes",
    "health": "Health",
    "здоровье": "Health",
    "medicine": "Health",
    "shopping": "Shopping",
    "shop": "Shopping",
    "магазин": "Shopping",
    "bills": "Bills",
    "internet": "Bills",
    "коммуналка": "Bills",
    "other": "Other",
    "другое": "Other"}

def get_current_month():
    return datetime.now().strftime("%B")

def normalize_category(category):
    category = category.lower().strip()
    return CATEGORIES.get(category,"Other")

def get_main_menu():
    markup = types.InlineKeyboardMarkup(row_width=2)
    btn_stats = types.InlineKeyboardButton(
        "📊 Statistics",
        callback_data="stats")
    btn_chart = types.InlineKeyboardButton(
        "📈 Chart",
        callback_data="chart")
    btn_categories = types.InlineKeyboardButton(
        "📂 Categories",
        callback_data="categories")
    btn_clear = types.InlineKeyboardButton(
        "🗑 Clear",
        callback_data="clear")
    markup.add(btn_stats, btn_chart)
    markup.add(btn_categories, btn_clear)
    return markup

def parse_multiple_expenses(text):
    lines = text.split("\n")
    parsed_expenses = []
    for line in lines:
        line = line.strip()
        if line == "":
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            amount = int(parts[0])
            category = normalize_category(parts[1])
            description = (
                " ".join(parts[2:])
                if len(parts) > 2
                else "No description")
            expense = {
                "amount": amount,
                "category": category,
                "description": description,
                "month": get_current_month()}
            parsed_expenses.append(expense)
        except:
            continue
    return parsed_expenses

def add_expenses(chat_id, expenses):
    if chat_id not in user_expenses:
        user_expenses[chat_id] = []
    user_expenses[chat_id].extend(expenses)

def calculate_statistics(chat_id):
    if(
        chat_id not in user_expenses
        or len(user_expenses[chat_id]) == 0):
        return None
    expenses = user_expenses[chat_id]
    total = 0
    category_totals = {}
    for expense in expenses:
        amount = expense["amount"]
        category = expense["category"]
        total += amount
        if category not in category_totals:
            category_totals[category] = 0
        category_totals[category] += amount
    return total, category_totals

def generate_smart_analysis(chat_id):
    result = calculate_statistics(chat_id)
    if result is None:
        return "❌ No expenses yet."
    total, category_totals = result
    sorted_categories = sorted(
        category_totals.items(),
        key=lambda x: x[1],
        reverse=True)
    top_category = sorted_categories[0][0]
    top_amount = sorted_categories[0][1]
    analysis = f"""
📊 EXPENSE ANALYSIS

💰 Total spent:
{total} KZT

🏆 Biggest category:
{top_category} — {top_amount} KZT

📂 Category breakdown:
"""
    for category, amount in sorted_categories:
        percent = (amount / total) * 100
        analysis += (
            f"\n• {category}: "
            f"{amount} KZT "
            f"({percent:.1f}%)")
    analysis += "\n\n🧠 Financial Insights:\n"
    if top_amount > total * 0.5:
        analysis += (
            f"• More than half of your expenses go to {top_category}.\n")

    if "Food" in category_totals:
        if category_totals["Food"] > 30000:
            analysis += (
                "• Food spending is relatively high.\n")

    if "Entertainment" in category_totals:
        if category_totals["Entertainment"] > 20000:
            analysis += (
                "• Entertainment expenses are above average.\n")

    if total > 100000:
        analysis += (
            "• Your overall spending is very high this month.\n")
    return analysis


    
        

