# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDm8WcmJL4jZhOa83AXgxeWY5ECaHOub
"""
!pip install pytelegrambotapi

import telebot
from telebot import types
from datetime import datetime
import matplotlib.pyplot as plt

MY_TOKEN = "8590324035:AAEIFPKl9zXyXfoch3zGNIG3yT8bvwB_4-0"

bot = telebot.TeleBot(MY_TOKEN)

user_expenses = {}
user_savings = {}

CATEGORIES = {
    "еда": "Food",
    "food": "Food",
    "кофе": "Food",
    "coffee": "Food",
    "restaurant": "Food",
    "кафе": "Food",
    "transport": "Transport",
    "транспорт": "Transport",
    "taxi": "Transport",
    "такси": "Transport",
    "bus": "Transport",
    "автобус": "Transport",
    "metro": "Transport",
    "entertainment": "Entertainment",
    "развлечения": "Entertainment",
    "movie": "Entertainment",
    "кино": "Entertainment",
    "games": "Entertainment",
    "sport": "Sport",
    "спорт": "Sport",
    "gym": "Sport",
    "fitness": "Sport",
    "education": "Education",
    "учеба": "Education",
    "books": "Education",
    "course": "Education",
    "clothes": "Clothes",
    "одежда": "Clothes",
    "shoes": "Clothes",
    "health": "Health",
    "здоровье": "Health",
    "medicine": "Health",
    "shopping": "Shopping",
    "shop": "Shopping",
    "магазин": "Shopping",
    "bills": "Bills",
    "internet": "Bills",
    "коммуналка": "Bills",
    "other": "Other",
    "другое": "Other"}

def get_current_month():
    return datetime.now().strftime("%B")

def normalize_category(category):
    category = category.lower().strip()
    return CATEGORIES.get(category,"Other")

def get_main_menu():
    markup = types.InlineKeyboardMarkup(row_width=2)
    btn_stats = types.InlineKeyboardButton(
        "📊 Statistics",
        callback_data="stats")
    btn_chart = types.InlineKeyboardButton(
        "📈 Chart",
        callback_data="chart")
    btn_categories = types.InlineKeyboardButton(
        "📂 Categories",
        callback_data="categories")
    btn_clear = types.InlineKeyboardButton(
        "🗑 Clear",
        callback_data="clear")
    markup.add(btn_stats, btn_chart)
    markup.add(btn_categories, btn_clear)
    return markup

def parse_multiple_expenses(text):
    lines = text.split("\n")
    parsed_expenses = []
    for line in lines:
        line = line.strip()
        if line == "":
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            amount = int(parts[0])
            category = normalize_category(parts[1])
            description = (
                " ".join(parts[2:])
                if len(parts) > 2
                else "No description")
            expense = {
                "amount": amount,
                "category": category,
                "description": description,
                "month": get_current_month()}
            parsed_expenses.append(expense)
        except:
            continue
    return parsed_expenses

def add_expenses(chat_id, expenses):
    if chat_id not in user_expenses:
        user_expenses[chat_id] = []
    user_expenses[chat_id].extend(expenses)

def calculate_statistics(chat_id):
    if(
        chat_id not in user_expenses
        or len(user_expenses[chat_id]) == 0):
        return None
    expenses = user_expenses[chat_id]
    total = 0
    category_totals = {}
    for expense in expenses:
        amount = expense["amount"]
        category = expense["category"]
        total += amount
        if category not in category_totals:
            category_totals[category] = 0
        category_totals[category] += amount
    return total, category_totals

def generate_smart_analysis(chat_id):
    result = calculate_statistics(chat_id)
    if result is None:
        return "❌ No expenses yet."
    total, category_totals = result
    sorted_categories = sorted(
        category_totals.items(),
        key=lambda x: x[1],
        reverse=True)
    top_category = sorted_categories[0][0]
    top_amount = sorted_categories[0][1]
    analysis = f"""
📊 EXPENSE ANALYSIS

💰 Total spent:
{total} KZT

🏆 Biggest category:
{top_category} — {top_amount} KZT

📂 Category breakdown:
"""
    for category, amount in sorted_categories:
        percent = (amount / total) * 100
        analysis += (
            f"\n• {category}: "
            f"{amount} KZT "
            f"({percent:.1f}%)")
    analysis += "\n\n🧠 Financial Insights:\n"
    if top_amount > total * 0.5:
        analysis += (
            f"• More than half of your expenses go to {top_category}.\n")

    if "Food" in category_totals:
        if category_totals["Food"] > 30000:
            analysis += (
                "• Food spending is relatively high.\n")

    if "Entertainment" in category_totals:
        if category_totals["Entertainment"] > 20000:
            analysis += (
                "• Entertainment expenses are above average.\n")

    if total > 100000:
        analysis += (
            "• Your overall spending is very high this month.\n")
    return analysis

def generate_financial_advice(chat_id):
    result = calculate_statistics(chat_id)
    if result is None:
        return "❌ Add some expenses first."
    total, category_totals = result
    advice = "💡 PERSONAL FINANCIAL ADVICE\n\n"
    sorted_categories = sorted(
        category_totals.items(),
        key=lambda x: x[1],
        reverse=True)

    top_category = sorted_categories[0][0]
    top_amount = sorted_categories[0][1]

    advice += (
        f"1️⃣ Your biggest spending category is {top_category} "
        f"with {top_amount} KZT spent. "
        f"Try setting a monthly limit for this category.\n\n")

    if "Food" in category_totals:

        advice += (
            "2️⃣ Food expenses can often be reduced by meal planning "
            "and avoiding daily coffee or delivery purchases.\n\n")

    if "Entertainment" in category_totals:

        advice += (
            "3️⃣ Entertainment spending should ideally stay below "
            "15-20% of your total budget.\n\n")

    if "Shopping" in category_totals:

        advice += (
            "4️⃣ Shopping expenses may include impulsive purchases. "
            "Try waiting 24 hours before buying non-essential items.\n\n")

    if chat_id in user_savings:
        savings = user_savings[chat_id]
        advice += (
            f"5️⃣ You are currently saving for: "
            f"{savings['goal']}. "
            "Consistent weekly savings will help you reach your goal faster.\n\n")
    else:
        advice += (
            "5️⃣ You currently do not have a savings goal. "
            "Setting one can improve financial discipline.\n\n")

    advice += (
        "6️⃣ A good financial strategy is:\n"
        "• 50% needs\n"
        "• 30% wants\n"
        "• 20% savings\n\n"
        "Track your expenses weekly to avoid overspending.")

    return advice

def create_chart(chat_id):
    result = calculate_statistics(chat_id)
    if result is None:
        return None
    total, category_totals = result
    labels = list(category_totals.keys())
    amounts = list(category_totals.values())
    plt.figure(figsize=(9, 9))
    colors = plt.cm.Set3(range(len(labels)))
    plt.pie(
        amounts,
        labels=labels,
        autopct='%1.1f%%',
        startangle=90,
        colors=colors)
    plt.title(
        "Expense Distribution",
        fontsize=16,
        fontweight='bold')
    plt.axis('equal')
    filename = f"chart_{chat_id}.png"
    plt.savefig(filename)
    plt.close()
    return filename
    
        

